blog/urls.py
from django.urls import path
from . import views

# Django server wants a app name
# Don't know why but this works
app_name = 'blog'

urlpatterns = [
    path('', views.post_list, name='post_list'),
    path('<int:id>', views.post_detail, name='post_detail'),
    path('tags=<slug:tag>', views.post_by_tag, name='post_by_tag'),
    path('category=<slug:category>', views.post_by_category, name='post_by_category'),
]

meals/urls.py
# Connect to main url in project folder
from django.urls import path
from . import views

# Django server wants a app name
# Don't know why but this works
app_name = 'meals'

urlpatterns = [
    path('', views.meal_list, name='meal_list'),
    path('<slug:slug>', views.meal_detail, name='meal_detail')
]

project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('meals/', include('meals.urls', namespace='meals')),
    path('blog/', include('blog.urls', namespace='blog')),
    path('reserve_table/', include('reservation.urls', namespace='reservation')),
] 

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

reservation/urls.py
# Connect to main url in project folder
from django.urls import path
from . import views

# Django server wants a app name
# Don't know why but this works
app_name = 'reservation'

urlpatterns = [
    path('', views.reserve_table, name='reserve_table'),
   
]

blog/models.py
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User
from taggit.managers import TaggableManager

# Structure for blog
class Post(models.Model):
    title = models.CharField(max_length=50)
    content = models.TextField() 
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    image = models.ImageField(upload_to='blog/', blank=True, null=True) 
    category = models.ForeignKey('Category', on_delete=models.SET_NULL, null=True)
    created = models.DateTimeField(default=timezone.now)
    tags = TaggableManager(blank=True)

    def __str__(self):
        return self.title

# Groups blog posts into different types
class Category(models.Model):
    category_name = models.CharField(max_length=50)

    # Fixes blog subscategory spelling error
    class Meta:
        verbose_name = 'Category'
        verbose_name_plural = 'Category'

    def __str__(self):
        return self.category_name


# Comments model 
class Comment(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    content = models.TextField()
    created = models.DateTimeField(default=timezone.now)

    def __str__(self):
        return self.content

meals/models.py
from django.db import models
from django.utils.text import slugify



# Structure for meal information
class Meals(models.Model):
    name = models.CharField(max_length=50)
    category = models.ForeignKey('Category', on_delete=models.SET_NULL, null=True) # Link meals to category. SET_NULL stops category from getting deleted when deleting a meal
    description = models.TextField(max_length=500)
    people = models.IntegerField()
    price = models.DecimalField(max_digits=5, decimal_places=2)
    preperation_time = models.IntegerField()
    image = models.ImageField(upload_to='meals/')
    slug = models.SlugField(blank=True, null=True)

    def save(self, *args, **kwargs):
        if not self.slug and self.name:
            self.slug = slugify(self.name)
        super(Meals, self).save(*args, **kwargs)

    # Fixes meals subscategory spelling error
    class Meta:
        verbose_name = 'meal'
        verbose_name_plural = 'meals'

    # name of meal appears in admin
    def __str__(self):
        return self.name




# Structure for food category menu ie. Breakfast, Lunch, Dinner
class Category(models.Model):
    name = models.CharField(max_length=30)

    # # Fixes Category subscategory spelling error
    class Meta:
        verbose_name = 'Category'
        verbose_name_plural = 'Categories'

    # Name of category appears in admin
    def __str__(self):
        return self.name

reservation/models.py
from django.db import models

# Structure for reservation model
class Reservation(models.Model):
    name = models.CharField(max_length=50)
    email = models.EmailField()
    phone = models.IntegerField()
    number_of_people = models.IntegerField()
    date = models.DateField()
    time = models.TimeField()

    def __str__(self):
        return self.name
    

blog/forms.py
from django import forms
from .models import Comment

class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = [
            'content'
        ]

reservation/forms.py
from django import forms
from .models import Reservation

class ReserveTableForm(forms.ModelForm):
    class Meta:
        model = Reservation
        fields = '__all__'

blog/views.py
from django.shortcuts import render
from .models import Post, Category, Comment
from taggit.models import Tag
from .forms import CommentForm

def post_list(request):
    post_list = Post.objects.all()

    context = {
        'post_list': post_list,
    }

    return render(request, 'Post/post_list.html', context)


def post_detail(request, id):
    post_detail = Post.objects.get(id=id)
    categories = Category.objects.all()
    all_tags = Tag.objects.all()
    comments = Comment.objects.filter(post=post_detail)
    

    if request.method == 'POST' :
        comment_form = CommentForm(request.POST)
        if comment_form.is_valid():
            new_comment = comment_form.save(commit=False)
            new_comment.user = request.user
            new_comment.post = post_detail
            new_comment.save()

    else:
        comment_form = CommentForm()

    context = {
        'post_detail' : post_detail,
        'categories': categories,
        'all_tags': all_tags,
        'comments': comments,
        'comment_form': comment_form,
    }

    return render(request, 'Post/post_detail.html', context)


def post_by_tag(request, tag):
    post_by_tag = Post.objects.filter(tags__name__in=[tag])
    context = {
        'post_list': post_by_tag,
    }

    return render(request, 'Post/post_list.html', context)




def post_by_category(request, category):
    post_by_category = Post.objects.filter(category__category_name=category)
    context = {
        'post_list': post_by_category,
    }

    return render(request, 'Post/post_list.html', context)

meals/views.py
from django.shortcuts import render
from .models import Meals, Category

# Displays list of all meals and categories
def meal_list(request):
    meal_list = Meals.objects.all()
    categories = Category.objects.all()

    # Connect variables for the views to the template
    context = {
        'meal_list' : meal_list,
        'categories' : categories,
    }


    # Render to html
    return render(request, 'Meals/list.html', context)




# Displays details of a meal using slug url
def meal_detail(request, slug):
    meal_detail = Meals.objects.get(slug=slug)

    # Connect variables for the views to the template
    context = {'meal_detail' : meal_detail}

    # Render to html
    return render(request, 'Meals/detail.html', context)

reservation/views.py
from django.shortcuts import render
from .models import Reservation
from reservation.models import Reservation
from .forms import ReserveTableForm

def reserve_table(request):

    reserve_form = ReserveTableForm()

    if request.method == 'POST':
        reserve_form = ReserveTableForm(request.POST)

        if reserve_form.is_valid():
            reserve_form.save()

    
    context = {'form': reserve_form}
    return render(request, 'Reservation/reservation.html', context)

blog/templates/Post/post_detail.html
{% extends 'base.html' %}
{% load static %}
{% block body %}
      
      <div class="main-wrap">
        <div class="cover_1 cover_sm">
          <div class="img_bg" style="background-image: url({% static 'site_static/img/slider-1.jpg' %})"
          data-stellar-background-ratio="0.5">
            <div class="container">
              <div class="row align-items-center justify-content-center">
                <div class="col-md-7 text-center" data-aos="fade-up">
                  <h2 class="heading mb-4">{{ post_detail }}</h2>

                  <div class="post-info">
                    <div class="date-info">{{post_detail.created}}</div>
                    <div class="category-info"><span class="seperator">|</span>In <a href="#" data-title="View all posts in Lifestyle" title="View all posts in Lifestyle">{{post_detail.category}}</a></div>
                    <div class="author-info"><span class="seperator">|</span>By <a href="#">{{post_detail.author}}</a></div>
                  </div>

                </div>
              </div>
            </div>
          </div>
        </div> <!-- .cover_1 -->

       <div class="section">
          <div class="container">
            
            <div class="row">

              <div class="col-md-8">
                <p>{{post_detail.content}}</p>  

                <div class="tag-widget post-tag-container mb-5 mt-5">
                  <div class="tagcloud">

                  {% for tag in post_detail.tags.all %}
                    <a href="{% url 'blog:post_by_tag' tag %}" class="tag-cloud-link">{{tag.name}}</a>
                  {% endfor %}
                  </div>
                </div>


                <div class="pt-5 mt-5">
                  <h3 class="mb-5">Comments</h3>
                  <ul class="comment-list">

                    {% for comment in commments %}
                      <li class="comment">
                        <div class="vcard bio">
                          <img src="img/person_1.jpg" alt="Image placeholder">
                        </div>
                        <div class="comment-body">
                          <h3>{{comment.user}}</h3>
                          <div class="meta">{{comment.created}}</div>
                          <p>{{comment.content}}</p>
                        </div>





                      </li>
                    {% endfor %}
                  </ul>
                  <!-- END comment-list -->
                  
                  <div class="comment-form-wrap pt-5">
                    <h3 class="mb-5">Leave a comment</h3>
                    <form method="POST" class="p-5 bg-light">
                      {% csrf_token %}
                      {{comment_form}}
                      <button type="submit" class="btn btn-primary">leave comment</button>
                    </form>
                  </div>
                </div>

              </div> <!-- .col-md-8 -->
              <div class="col-md-4 sidebar">
                <div class="sidebar-box">
                  <form action="#" class="search-form">
                    <div class="form-group">
                      <span class="icon fa fa-search"></span>
                      <input type="text" class="form-control" placeholder="Type a keyword and hit enter">
                    </div>
                  </form>
                </div>

                <div class="sidebar-box">
                  <div class="categories">
                    <h3>Categories</h3>
                    {% for category in categories %}
                    
                    <li><a href="{% url 'blog:post_by_category' category %}">{{category}}</a></li>

                    {% endfor %}
                  </div>
                </div>
                

                <div class="sidebar-box">
                  <h3>Tag Cloud</h3>
                  <div class="tagcloud">
                  {% for tag in all_tags %}
                    <a href="{% url 'blog:post_by_tag' tag %}" class="tag-cloud-link">{{tag}}</a>
                  {% endfor %}
              
                  </div>
                </div>

                
              </div>

            </div>

            
          </div>
        </div> <!-- .section -->
      


      </div> <!-- .main-wrap -->
      

      {% endblock body %}

blog/templates/Post/post_list.html
{% extends 'base.html' %}
{% load static %}
{% block body %}

<div class="main-wrap">
  <div class="cover_1 cover_sm">
    <div class="img_bg" style="background-image: url({% static 'site_static/img/slider-1.jpg' %})"
      data-stellar-background-ratio="0.5">
      <div class="container">
        <div class="row align-items-center justify-content-center">
          <div class="col-md-7" data-aos="fade-up">
            <h2 class="heading">Blog Grid</h2>
            <p class="lead">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Nemo saepe dolorum dolorem, iste
              officia voluptates! Sint repudiandae, soluta voluptatem delectus iure, eaque, harum expedita, nisi aliquam
              magni odio perferendis ipsum!</p>
          </div>
        </div>
      </div>
    </div>
  </div> <!-- .cover_1 -->

  <div class="section">
    <div class="container">

      <div class="row mb-5">

        {% for post in post_list %}
        <div class="col-md-4">
          <div class="media d-block media-bg-white mb-5" data-aos="fade-up" data-aos-delay="400">
            <figure>
              <a href="blog-single.html"><img src="{{post.image.url}}" alt="Image placeholder" class="img-fluid"></a>
            </figure>
            <div class="media-body">
              <h3><a href="{% url 'blog:post_detail' post.id %}">{{post}}</a></h3>
              <p class="post-meta"><span><span class="fa fa-calendar"></span> {{post.created}}</span></p>
              <p class="mb-4">{{post.content}}</p>
              <p><a href="{% url 'blog:post_detail' post.id %}" class="btn btn-primary btn-outline-primary btn-sm">Read More</a></p>
            </div>
          </div> <!-- .media -->
        </div>
        {% endfor %}


      </div>

      <div class="row">
        <div class="col-md-12">
          <ul class="pagination custom-pagination">
            <li class="page-item prev"><a class="page-link" href="#"><i class="fa fa-angle-left"></i></a></li>
            <li class="page-item active"><a class="page-linkx href=" #">1</a></li>
            <li class="page-item"><a class="page-link" href="#">2</a></li>
            <li class="page-item"><a class="page-link" href="#">3</a></li>
            <li class="page-item next"><a class="page-link" href="#"><i class="fa fa-angle-right"></i></a></li>
          </ul>


        </div>
      </div>
    </div>
  </div> <!-- .section -->



</div> <!-- .main-wrap -->


{% endblock body %}

meals/templates/Meals/list.html
{% extends 'base.html' %}
{% load static %}
{% block body %}

<div class="main-wrap">
  <div class="cover_1">
    <div class="img_bg" style="background-image: url({% static 'site_static/img/slider-1.jpg' %})"
      data-stellar-background-ratio="0.5">
      <div class="container">
        <div class="row align-items-center">
          <div class="col-md-12" data-aos="fade-up">
            <h2 class="heading">Lorem ipsum dolor sit amet consectetur adipisicing elit. Fugit ipsa sint amet aliquam
              velit minima tenetur quisquam beatae molestiae possimus dicta.</h2>
          </div>
        </div>
      </div>
    </div>
  </div> <!-- .cover_1 -->


  {% comment %}
  <div class="section">
    <div class="container">
      <div class="row justify-content-center">
        <div class="col-md-7 text-center" data-aos="fade-up">
          <h2 class="mb-4">Our Specialties</h2>
          <p class="lead">Lorem ipsum dolor sit amet consectetur adipisicing elit. Beatae eum voluptatem odio expedita
            laborum fugit repudiandae dolorem consectetur.</p>
        </div>
      </div>
    </div>
  </div> <!-- .section -->

  <div class="section pt-0 pb-0">

    <div class="menus d-flex bg-light">
      <div class="d-flex item">
        <div class="image" style="background-image: url(img/img_1.jpg);" data-aos="fade"></div>
        <div class="text">
          <h3>Grilled Egg With Garlic</h3>
          <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Consequuntur illo quisquam saepe quaerat.</p>
          <p class="price">$5.00</p>
        </div>
      </div> <!-- .item -->

      <div class="d-flex item">
        <div class="image order-2 order-md-1" style="background-image: url(img/img_2.jpg);" data-aos="fade"
          data-aos-delay="100"></div>
        <div class="text order-1 order-md-2">
          <h3>Organic Tomato Salad</h3>
          <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Consequuntur illo quisquam saepe quaerat.</p>
          <p class="price">$6.00</p>
        </div>
      </div> <!-- .item -->

      <div class="d-flex item">
        <div class="image order-1 order-md-2 order-lg-2 order-xl-1" style="background-image: url(img/img_3.jpg);"
          data-aos="fade" data-aos-delay="200"></div>
        <div class="text order-2 order-md-1 order-lg-1 order-xl-2">
          <h3>Flatbread</h3>
          <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Consequuntur illo quisquam saepe quaerat.</p>
          <p class="price">$9.00</p>

        </div>
      </div> <!-- .item -->

      <div class="d-flex item">
        <div class="image order-2" style="background-image: url(img/img_4.jpg);" data-aos="fade" data-aos-delay="300">
        </div>
        <div class="text order-1 mb-3">
          <h3>Rack Of Lamb</h3>
          <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Consequuntur illo quisquam saepe quaerat.</p>
          <p class="price">$13.00</p>
        </div>
      </div> <!-- .item -->

      <div class="d-flex item">
        <div class="image order-1 order-lg-1 order-xl-2" style="background-image: url(img/img_5.jpg);" data-aos="fade"
          data-aos-delay="400"></div>
        <div class="text order-2 order-lg-2 order-xl-1">
          <h3>Eggplant Parmigiana</h3>
          <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Consequuntur illo quisquam saepe quaerat.</p>
          <p class="price">$9.00</p>
        </div>
      </div> <!-- .item -->

      <div class="d-flex item">
        <div class="image order-2 order-md-1 order-lg-1 order-xl-2" style="background-image: url(img/img_6.jpg);"
          data-aos="fade" data-aos-delay="500"></div>
        <div class="text order-1 order-md-2 order-lg-2 order-xl-1">
          <h3>Spicy Meatballs</h3>
          <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Consequuntur illo quisquam saepe quaerat.</p>
          <p class="price">$7.00</p>
        </div>
      </div> <!-- .item -->

    </div>
  </div>


  {% endcomment %}

  <div class="section">
    <div class="container">
      <div class="row justify-content-center">
        <div class="col-md-8" data-aos="fade-up">

          <h2 class="mb-5 text-center">Menu List with Price</h2>

          <ul class="nav site-tab-nav" id="pills-tab" role="tablist">
            {% for category in categories %}


            <li class="nav-item">
              <a class="nav-link" id="{{category}}-tab" data-toggle="pill" href="#{{category}}" role="tab"
                aria-controls="{{category}}" aria-selected="true">{{category}}</a>
            </li>
            {% endfor %}

          </ul>


          <div class="tab-content" id="pills-tabContent">


            {% for category in categories %}

            <div class="tab-pane fade show active" id="{{category}}" role="tabpanel" aria-labelledby="{{category}}-tab">

              {% for meal in meal_list %}
                {% if meal.category == category%}

              <div class="d-block d-md-flex menu-food-item">
                <div class="text order-1 mb-3">
                  <h3><a href="{% url 'meals:meal_detail' meal.slug %}">{{ meal.name }}</a></h3>
                  <p>{{ meal.description }}</p>
                </div>
                <div class="price order-2">
                  <strong>£{{ meal.price }}</strong>
                </div>
              </div> <!-- .menu-food-item -->
                {% endif %}

              {% endfor %}


            </div>

            {% endfor %}
          </div>


        </div>
      </div>
    </div>
  </div>





</div> <!-- .main-wrap -->

{% endblock body %}

templates/base.html
{% load static %}

<!doctype html>
<html lang="en">
  <head>
    <title>Colorlib Diner</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <link href="https://fonts.googleapis.com/css?family=Playfair+Display:300,400,700,800|Open+Sans:300,400,700" rel="stylesheet">

    <link rel="stylesheet" href="{% static 'site_static/css/bootstrap.css' %}">
    <link rel="stylesheet" href="{% static 'site_static/css/animate.css' %}">
    <link rel="stylesheet" href="{% static 'site_static/css/owl.carousel.min.css' %}">

    <link rel="stylesheet" href="{% static 'site_static/css/magnific-popup.css' %}">
    <link rel="stylesheet" href="{% static 'site_static/css/aos.css' %}">

    <link rel="stylesheet" href="{% static 'site_static/css/bootstrap-datepicker.css' %}">
    <link rel="stylesheet" href="{% static 'site_static/css/jquery.timepicker.css' %}">

    <link rel="stylesheet" href="{% static 'site_static/fonts/ionicons/css/ionicons.min.css' %}">
    <link rel="stylesheet" href="{% static 'site_static/fonts/fontawesome/css/font-awesome.min.css' %}">

    <link rel="stylesheet" href="{% static 'site_static/fonts/flaticon/font/flaticon.css' %}">

    <!-- Theme Style -->
    <link rel="stylesheet" href="{% static 'site_static/css/style.css' %}">
  </head>
  <body>
    

    <div class="site-wrap">
      
      <nav class="site-menu">
        <div class="site-menu-inner">
          <ul class="list-unstyled">
            <li class="active"><a href="index.html">Home</a></li>
            <li><a href="about.html">About Us</a></li>
            <li><a href="menu.html">Our Menu</a></li>
            <li><a href="blog.html">Our Blog</a></li>
            <li><a href="{% url 'reservation:reserve_table' %}">Reserve A Table</a></li>
            <li><a href="contact.html">Contact</a></li>
          </ul>
        </div>
      </nav>

      <header class="site-header">
        <div class="row align-items-center">
          <div class="col-5 col-md-3">
             <ul class="list-unstyled social">
              <li><a href="#"><span class="fa fa-facebook"></span></a></li>
              <li><a href="#"><span class="fa fa-twitter"></span></a></li>
              <li><a href="#"><span class="fa fa-instagram"></span></a></li>
            </ul>
          </div>
          <div class="col-2 col-md-6 text-center">
            <a href="index.html" class="site-logo">D</a>
          </div>
          <div class="col-5 col-md-3 text-right menu-burger-wrap">
            <a href="#" class="site-nav-toggle js-site-nav-toggle"><i></i></a>

          </div>
        </div>
       
      </header> <!-- site-header -->
    
      {% block body %}

      {% endblock body %}
      

      <footer>
        <div class="site-footer">
          <div class="container">
            <div class="row small-gutters mb-5">
              <div class="col-md-6 col-lg-3 mb-5" data-aos="fade" data-aos-delay="100">
                <div class="footer-widget">
                  <h3>Diner Restaurant</h3>
                  <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Vel neque, odio illum. Est minima sint minus sunt ducimus.</p>
                </div>
              </div>
              <div class="col-md-6 col-lg-3 mb-5" data-aos="fade" data-aos-delay="200">
                <div class="footer-widget">
                  <h3>Lunch Service</h3>
                  <p>Booking from 12:00pm - 1:30pm</p>
                  <h3>Dinner Service</h3>
                  <p>Everyday: <br> Booking from 6:00pm - 9:00pm</p>
                </div>
              </div>
              <div class="col-md-6 col-lg-3 mb-5" data-aos="fade" data-aos-delay="300">
                <div class="footer-widget">
                  <h3>Quick Links</h3>
                  <ul>
                    <li><a href="#">Help &amp; Support</a></li>
                    <li><a href="#">Privacy Policy</a></li>
                    <li><a href="#">Get in Touch</a></li>
                    <li><a href="#">Testimonials</a></li>
                  </ul>
                </div>
              </div>
              <div class="col-md-6 col-lg-3 mb-5" data-aos="fade" data-aos-delay="400">
                <div class="footer-widget footer-contact-widget">

                  <h3>Subscribe</h3>
                  <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit.</p>
                  <form action="" class="form-subscribe mb-5">
                    <div class="form-group form-field">
                      <input type="submit" value="Send" class="btn btn-primary">
                      <input type="text" class="form-control" placeholder="Email">
                    </div>
                  </form>

                  <h3>Contact Us</h3>
                  <p class="contact-email">info@yourdomain.com</p>
                  <p class="contact-phone">1-444-123-9829</p>
                  
                  
                </div>
              </div>
            </div>
          </div>
          
        </div>
      </footer>

      <div class="site-footer-copyright">
        <div class="container">
          <div class="row">

             <p class="footer-text col-md-12"><!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
Copyright &copy;<script>document.write(new Date().getFullYear());</script> All rights reserved | This template is made with <i class="fa fa-heart" aria-hidden="true"></i> by <a href="https://colorlib.com" target="_blank">Colorlib</a>
<!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. --></p>
          </div>
        </div>
      </div>

    </div>

    <!-- loader -->
    <div id="loader" class="show fullscreen"><svg class="circular" width="48px" height="48px"><circle class="path-bg" cx="24" cy="24" r="22" fill="none" stroke-width="4" stroke="#eeeeee"/><circle class="path" cx="24" cy="24" r="22" fill="none" stroke-width="4" stroke-miterlimit="10" stroke="#f4b214"/></svg></div>

    <script src="{% static 'site_static/js/jquery-3.2.1.min.js' %}"></script>
    <script src="{% static 'site_static/js/jquery-migrate-3.0.1.min.js' %}"></script>
    <script src="{% static 'site_static/js/popper.min.js' %}"></script>
    <script src="{% static 'site_static/js/bootstrap.min.js' %}"></script>
    <script src="{% static 'site_static/js/owl.carousel.min.js' %}"></script>
    <script src="{% static 'site_static/js/jquery.waypoints.min.js' %}"></script>

    <script src="{% static 'site_static/js/bootstrap-datepicker.js' %}"></script>
    <script src="{% static 'site_static/js/jquery.timepicker.min.js' %}"></script>
    <script src="{% static 'site_static/js/jquery.stellar.min.js' %}"></script>

    <script src="{% static 'site_static/js/aos.js' %}"></script>
    

    <script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyBVWaKrjvy3MaE7SQ74_uJiULgl1JY0H2s&sensor=false"></script>

    <script src="{% static 'site_static/js/main.js' %}"></script>
  </body>
</html>